### ISSUE TITLE
Adding License indicators of the dataset to the table

### ISSUE THREAD

**Issue by ogencoglu** [nicolasj92/industrial-ml-datasets#1]
Would be super helpful if the license (MIT, GPLv3, etc.) of these datasets are indicated as well. This would give a nice overview of which can be used commercial, for research-only etc.

**Comment by nicolasj92** [comment]
Hi, yes that is very true! When I find the time I will add license information if available. Unfortunately, I already know that there is no license information available on a significant portion of the datasets.

**Comment by nicolasj92** [comment]
We have added the licenses where available.
