### ISSUE TITLE
Additional dataset (SKAB)

### ISSUE THREAD

**Issue by YKatser** [nicolasj92/industrial-ml-datasets#2]
Probably https://github.com/waico/SKAB dataset may be appropriate for including in this repository. It is similar to Tennessee Eastman Process (Process Monitoring problem). Would you mind adding it? Generally a great repository, thanks.

**Comment by nicolasj92** [comment]
Hi, I agree, the dataset looks very interesting and seems to be a good fit to the collection! Would you mind creating a PR with the dataset added to the Process Monitoring table?
Best,
Nico
